# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Executes after build if request is pushing to main branch
  deploy:
    runs-on: ubuntu-latest
    # needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:

    # Get into server and start docker compose
    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PI_REMOTE_SSH_HOST }}
        username: ${{ secrets.PI_REMOTE_SSH_USERNAME }}
        key: ${{ secrets.PI_REMOTE_SSH_KEY }}
        port: ${{ secrets.PI_REMOTE_SSH_PORT }}
        script: |
          cd /home/${{ secrets.PI_REMOTE_SSH_USERNAME }}/Projects/snack-trip/coordipai-web-server
          git pull origin main
          cd /home/${{ secrets.PI_REMOTE_SSH_USERNAME }}/Projects
          docker system prune -f
          docker compose build coordipai-web-server
          docker compose up -d --no-deps coordipai-web-server

