name: Deploy FastAPI with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🏗️ Build Docker Image
        run: |
          docker build -t coordipai-web-server:latest .

      - name: 📂 Save Docker Image as tar
        run: |
          docker save -o coordipai-web-server.tar coordipai-web-server:latest
          chmod 644 coordipai-web-server.tar

      - name: 🚀 Copy Image to Remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          source: "coordipai-web-server.tar"
          target: "cd /home/${{ secrets.REMOTE_SSH_USERNAME }}/Projects/"
